apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sykmelder-statistikk
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.nav.no/samarbeidspartner/sykmelder-statistikk'
  liveness:
    path: /samarbeidspartner/sykmelder-statistikk/api/internal/is_alive
  readiness:
    path: /samarbeidspartner/sykmelder-statistikk/api/internal/is_ready
  startup:
    path: /samarbeidspartner/sykmelder-statistikk/api/internal/is_ready
    initialDelay: 20
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  idporten:
    enabled: true
    sidecar:
      enabled: true
      resources:
        requests:
          cpu: 100m
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 400m
      memory: 756Mi
  tokenx:
    enabled: true
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  env:
    - name: SYKMELDER_STATISTIKK_DB_INSTANCE
      value: teamsykmelding-prod-2acd:europe-north1:sykmelder-statistikk
  envFrom:
    - secret: google-sql-sykmelder-statistikk-kafka-statistikk-sykme-fc9e33bd
