apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sykmelder-statistikk
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.ekstern.dev.nav.no/samarbeidspartner/sykmelder-statistikk'
  liveness:
    path: /samarbeidspartner/sykmelder-statistikk/api/internal/is_alive
  readiness:
    path: /samarbeidspartner/sykmelder-statistikk/api/internal/is_ready
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  idporten:
    enabled: true
    sidecar:
      enabled: true
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 100m
      memory: 512Mi
  tokenx:
    enabled: true
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: decorator-next
          namespace: personbruker
  env:
    - name: SYKMELDER_STATISTIKK_DB_INSTANCE
      value: teamsykmelding-dev-1d34:europe-north1:sykmelder-statistikk
  envFrom:
    - secret: google-sql-sykmelder-statistikk-kafka-statistikk-sykme-fc9e33bd
