apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: {{appname}}-demo
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
    branchState: {{branchState}}
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - {{ingress}}
  replicas:
    min: {{replicas}}
    max: {{replicas}}
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi
  liveness:
    path: /samarbeidspartner/sykmelder-statistikk/api/internal/is_alive
  readiness:
    path: /samarbeidspartner/sykmelder-statistikk/api/internal/is_ready
  accessPolicy:
    outbound:
      external:
        - host: nav.no
        - host: dekoratoren.nav.no
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
