apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sykmelder-statistikk-database-network-policy
  namespace: teamsykmelding
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 35.228.138.140/32
  podSelector:
    matchLabels:
      app: sykmelder-statistikk
  policyTypes:
    - Egress
