name: Build & Deploy
on: push

permissions:
  actions: read
  contents: read
  security-events: write
  packages: write
  id-token: write

jobs:
  next-app:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/next-app.yaml@node-20
    secrets: inherit
    with:
      app: sykmelder-statistikk
      base-path: /samarbeidspartner/sykmelder-statistikk
